micronaut:
  application:
    name: unity-iam
  security:
    authentication: bearer
datasources:
  default:
    url: jdbc:mysql://localhost:13306/test?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test
    db-type: mysql
flyway:
  datasources:
    default:
      enabled: true