micronaut:
  application:
    name: unity-iam
  security:
    authentication: bearer
datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
flyway:
  datasources:
    default:
      enabled: true
