micronaut:
  application:
    name: unity-iam
  security:
    endpoints:
      logout:
        path: /api/logout
        get-allowed: true
      login:
        path: /api/login
    intercept-url-map:
      - pattern: /api/login
        http-method: POST
        access:
          - isAnonymous()
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${UNITY_SIGNATURE_SECRET:123456789012345123456789012345123456789012345123456789012345123456789012345}"'
datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
flyway:
  datasources:
    default:
      enabled: true
